name: build
on: [push, workflow_dispatch]
jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build Zhuque Fangsong
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build fonts
        run: |
          cd src
          bash build.sh
      - name: Upload fonts
        uses: actions/upload-artifact@v6
        with:
          name: ZhuqueFangsong
          path: fonts
